### PR TITLE
bug fix? %5B345%5D or '[345]' in js url ?

### PR DESCRIPTION
**Pull request by wrightlabs**
Not sure what this was. Url encoded '[345]', but when I removed it, the js version of the plugin worked for me.

### CODE REVIEW

**Comment by muloka** [comment]
Looks like this project has been put on hold for now?

**Comment by simensen** [comment]
I apologize for the delay on this. I'll see what I can do to get it up to wordpress ASAP.

**Comment by simensen** [comment]
Alright, this is in at version 0.10.

**Comment by muloka** [comment]
Wicked.

**Pull request merged**
